
spring:
  profiles:
    active:
    - dev
---
spring:
  application:
    name: config-7001
  profiles: dev
   
server:
  port: 7001
  
feign:
  hystrix:
    enabled: true     #启用服务降级
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/   # 注册中心地址
      
      
---

spring:
  application:
    name: config-7002
  profiles: test
 
server:
  port: 7002 
  
feign:
  hystrix:
    enabled: true     #启用服务降级
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/   # 注册中心地址
