
server:
  port: 7001

spring:
  profiles:
    active:
    - dev
  
feign:
  hystrix:
    enabled: true     #启用服务降级
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/   # 注册中心地址
      
      
---

server:
  port: 7002

spring:
  profiles:
    active:
    - test
  
feign:
  hystrix:
    enabled: true     #启用服务降级
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/   # 注册中心地址
