spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-dept-client-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.106:3306/springcloud?characterEncoding=UTF-8&useSSL=true              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      validation-query: SELECT 1
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.itany.entity                    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept-8001-instance-client-dev             #euarkea 主机名称修改
    prefer-ip-address: true
    
# info 信息的改善    
info: 
  app.name: itany-cloud
  company.name: www.hanhui.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
logging:
  level:
   com.itany.dao.DeptDao: DEBUG

  

---

spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-dept-client-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.106:3306/springcloud01?characterEncoding=UTF-8&useSSL=true              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      validation-query: SELECT 1

server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.itany.entity                    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept-8001-instance-client-test             #euarkea 主机名称修改
    prefer-ip-address: true
    
# info 信息的改善    
info: 
  app.name: itany-cloud
  company.name: www.hanhui.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
logging:
  level:
   com.itany.dao.DeptDao: DEBUG
